### ISSUE TITLE
Error not very descriptive

### ISSUE THREAD

**Issue by felixsanz** [Qix-/color#103]
When you pass a CSS color instead of a `color` instance to (at least) the `mix` function, the error is not very descriptive.

```javascript
myColor.mix('black', 0.6) // should be myColor.mix(color('black'), 0.6)

> TypeError: mixinColor.rgb is not a function // wat?
```

This is the kind of bug that make you waste a lot of time. In fact, I'm going to add this picture here.

![Typo](https://image.spreadshirtmedia.com/image-server/v1/compositions/1013700807/views/1,width=300,height=300,appearanceId=2,version=1479367045/software-development-process-shirt-men-s-t-shirt.jpg)

**Comment by Qix-** [comment]
Hi - I'm not sure how to accommodate this other than to do an `instanceof` check, which breaks the whole idea of dynamic languages (e.g. if another library wants to be compatible with this library, they could implement the `rgb()` function).

Personally, I find the error pretty revealing: `mixinColor` (the color you're trying to mix in, in this case `'black'`) does not have a function called `.rgb()` - which makes sense, because it's a string.

I'm sorry for the grief it might have caused you but I don't see how this could be any more clearer without doing some sort of type checking...

**Comment by felixsanz** [comment]
Maybe checking `if (mixinColor.rgb === undefined)` and returning `return new Error('The color passed is not a valid color instance')`.

Something like that?

**Comment by RobertFischer** [comment]
I just ran into this issue because I assumed arguments that were passed in would be converted to `Color` instances.
