### ISSUE TITLE
It's not working with karma

### ISSUE THREAD

**Issue by heikoholland** [Qix-/color#105]
I'm writing unit tests for my Ionic2 app and somehow karma is messing things up. I found the error but I don't understand why this is happening.

I changed the first lines in `color-convert` module (https://github.com/Qix-/color-convert):
```
var conversions = require('./conversions');
console.log(Object.keys(conversions));
```
The output in Chrome is `["rgb", "hsl", "hsv", "hwb", "cmyk", "xyz", "lab", "lch", "hex", "keyword", "ansi16", "ansi256", "hcg", "apple", "gray"]`
The output in karma is `['rgb', 'hsl', 'hsv', 'hwb', 'cmyk', 'xyz', 'lab', 'lch', 'hex', 'keyword', 'ansi16', 'ansi256', 'hcg', 'apple', 'gray', 'default']`

So the problem is that there is a `default` property is added during `module.exports`.

I workaround this bug with deleting the property in `color/index.js` like:
```
var convert = require('color-convert');
delete convert.default;
```

**Comment by Qix-** [comment]
Err, apologies but I don't see how this is Color's problem. Karma or Ionic2 should be notified of this _gigantic_ bug. They shouldn't be adding enumerable properties to anything.

Deleting `.default` is a hack and introduces technical debt - and isn't going to benefit many people in the long run.

Please file a bug with either Karma or Ionic2 - feel free to link to this issue as well and I will gladly chime in as I can guarantee you this wouldn't be the only module affected.

Further, can you confirm this is actually a problem on Karma/Ionic2's side and not your own?

**Comment by hkeio** [comment]
Yep, I don't think that this is Color's problem but I just wanted to let you know that there is some thing not working in this particular setup and show a (definitely temporary but not acceptable) solution. I created a repo which represents this issue: https://github.com/hkeio/ionic2-test-app/tree/karma-misbehavior

> Further, can you confirm this is actually a problem on Karma/Ionic2's side and not your own?

I didn't do much in the mentioned repo yet. I just started a new Ionic2 project and followed the instructions from this guide (http://www.joshmorony.com/how-to-unit-test-an-ionic-2-application/) to install karma.
At this moment I only experienced issues with Ionic2 and karma with your module but I guess it's because no other module loops through returned value of a `require`.

I'm not quite sure that this is a karma or Ionic issue or it's webpacks fault. What do you think? I don't want to open issues in every project.

**Comment by Qix-** [comment]
Whichever project is tacking on the `default` property to modules is the one that should be patched.

**Comment by Qix-** [comment]
Closing as `wontfix` - this is not a problem of this module. Please file against the offending framework(s)' repository.
