### ISSUE TITLE
How to use return hex string instead of hsl ?

### ISSUE THREAD

**Issue by kopax** [Qix-/color#109]
Is it possible to convert hex string instead of HSL?

**Comment by Qix-** [comment]
What's wrong with `Color('hsl(...)').hex()`?

**Comment by kopax** [comment]
Thanks, couldn't find it in the documentation.

**Comment by thealjey** [comment]
@kopax because it's not there :)
```javascript
color('#000').blacken(.5) !== color('#000').whiten(.5)
color('#000').blacken(.5).hex() === color('#000').whiten(.5).hex()
```
`hex()`always returns the same value basically

I just don't understand why this package is so popular if the most basic things do not work

**Comment by Qix-** [comment]
@thealjay your misunderstanding of color spaces and the intent of the API, along with basic JavaScript concepts, is not indicative of this package not working.

**Comment by thealjey** [comment]
@Qix- I may not know a whole lot about colors, but, trust me, I do know javascript pretty well
can you please, instead of throwing offensive remarks at me, elaborate, how is it that you lighten a color and you darken a color, but it's hex always remains the same?
the `hex` function is not even documented at all
clearly, this project is maintained by the most professional people in the world

**Comment by Qix-** [comment]
> I just don't understand why this package is so popular if the most basic things do not work

No need to insult this package then.

`.blacken()` and `.whiten()` are for the HWB color space. These functions have been discussed [at length](https://github.com/Qix-/color/issues/82). They work as expected, and thus is why people still use this package.

Further, performing equality on two objects will never yield true unless they are the same exact object. This is especially true for `color` since this module results in immutable objects.

There are no bugs here. If you have an idea on how to better namespace the API, by all means discuss that. But a simple issues search would have yielded you the correct answer to your question.
