### ISSUE TITLE
Explain getset function

### ISSUE THREAD

**Issue by kiru** [Qix-/color#110]
Hello @Qix- , 

Thank you for this library, it is really useful in our project. 

I tried to read the source  ( how the 'darken' function was implemented, but struggled to find the origin of the 'hsv' function). 
Later we found the 'getset' (https://github.com/Qix-/color/blob/master/index.js#L428) function. Could you give me  short explanation of getset? 
Why is the 'hsv' function not defined regularly like the darken function?

Thanks a lot, 
Kiru

**Comment by Qix-** [comment]
Hi - great question.

A lot of the methods in a `Color` object simply get or set a particular value for a channel. The way the methods are used is that if there is an argument passed to the method, it's considered a setter. If not, it's considered a getter.

This design choice was to keep API backwards compatibility from version 0.x to version 1.x, as well as helping to keep lengthy manipulations a bit shorter syntactically.

Since there are many channel getters/setters, a LOT of code would be repeated. Therefore, `getset` is just a helper function that constructs a getter/setter function as described above, configured for different models as well as a few other things like acceptable domains, etc.

This is all part of the [DRY](https://en.m.wikipedia.org/wiki/Don't_repeat_yourself) line of thinking.

Good question!
