### ISSUE TITLE
Does this package work in Angular 7?

### ISSUE THREAD

**Issue by nithincn89** [Qix-/color#160]
I have my application in Angular 7. After installing this package and importing it to the application, it is not working properly.

When I am using the following command 'var color = Color('rgb(255, 255, 255)')' , I am getting following error in the console. 

ERROR TypeError: Object(...) is not a function

Can anyone check this and help to solve the issue?

**Comment by dlasagno** [comment]
I used this package with typescript and it was working, can you provide the import line? Maybe it is the problem.

**Comment by nithincn89** [comment]
Thanks for your reply. I used the following method to import it.

import { Color } from 'color';

Is it causes the problem? Then please guide me with the right way.

**Comment by dlasagno** [comment]
Yes, it is the problem.
This is the right way of importing the package:
```javascript
import * as Color from 'color'
```
The problem is that the syntax that you used works only if the package `'color'` exports an object with an entry named `Color`. But since `'color'` exports a function typescript(or javascript) can't apply an _object_ destructuring to it.
By using the above syntax you just take whatever `'color'` exports and you name it `'Color'`.

> If you want to find out more on the subject I suggest you to read this: [https://medium.com/backticks-tildes/introduction-to-es6-modules-49956f580da](https://medium.com/backticks-tildes/introduction-to-es6-modules-49956f580da)

**Comment by nithincn89** [comment]
@dlasagno That's work great. Thanks for your guidance and solution.

**Comment by Qix-** [comment]
Glad you got it figured out.
