### ISSUE TITLE
How do I invert colors?

### ISSUE THREAD

**Issue by hendrul** [Qix-/color#162]
Invert colors, e.g. get the oposite color, is a must have, don't you think?

**Comment by Qix-** [comment]
There isn't one way to invert a color. If you're talking about a an effect like a film negative, there isn't a whole lot of everyday practical value in such a function. I'll leave it up to you as an exercise ;)

**Comment by iDVB** [comment]
Currently in a situation that we are designing a themed component that needs some of the design to have lines that are inverted from the background color that is dynamic. In the simplest cast... white background would be black lines.... or black background would be white lines. 

In more complex scenerios I believe this is called [complimentary colors](https://en.wikipedia.org/wiki/Complementary_colors) which when it comes to theme engines is very common. Someone even build [another nom module](https://github.com/onury/invert-color) to handle just this.

@Qix- Your `color` module has long since been my defacto go to for all things color manipulations related. adding a function for complimentary colors would be amazing.

**Comment by Qix-** [comment]
Inversion can be a complimentary color huge shift or a color channel negation (`1-c`) - "invert" isn't really specified here. What is the "opposite color" in this case?

That's my point. :) 

For complimentary colors, simply rotate the hue by 180 degrees: `color.rotate(180)`.

For one-minus inversion, just call `color.negate()`. Other forms of inversion aren't common and thus don't really warrant their own functions.
