### ISSUE TITLE
Adding Tetradic and Triadic color palette generator

### ISSUE THREAD

**Issue by schie** [Qix-/color#212]
Hello!

I find myself constantly creating Tetradic and Triadic color palette w/ this library in numerous projects I work on. 

Would you find any benefit in adding these to this lib?

For example:

```js
const inputColor = Color('#FFFF00');

const triadics = inputColor.triadicPalette(); // [Color('#FFFF00'), Color('#00FFFF'), Color('#FF00FF')]
const tetradics = inputColor.tetradicPalette(); // [Color('#FFFF00'), Color('#00FF80'), Color('#0000FF'), Color('#FF0080')]

```

#### Triadic
![Screen Shot 2021-08-08 at 11 27 48 PM](https://user-images.githubusercontent.com/4561856/128657560-98f3303e-435f-4376-86f0-035f7d43d7d5.png)

#### Tetradic
![Screen Shot 2021-08-08 at 11 28 39 PM](https://user-images.githubusercontent.com/4561856/128657585-bd2d0389-180c-422d-a223-56b70dfa0cb4.png)

If so, I'd be happy to make a PR.

**Comment by Qix-** [comment]
I'm on the fence about it, purely because it's not a commonly used feature (I understand you use it often but I haven't seen many examples of it elsewhere) and the library is already kind of stagnant because of the existing complicated API.

If you'd like to take the time to make a PR, that'd be great - just know that I might decide against it if it adds too much bulk.

**Comment by Qix-** [comment]
Hi, I've thought more about it and I don't think this fits within the scope of the package. Thanks for filing an issue though :)
