### ISSUE TITLE
Make Color objects immutable

### ISSUE THREAD

**Issue by ooflorent** [Qix-/color#56]
Making `Color` objects immutable would result in a leaner API:

``` js
// Mutable
const red = Color('#ee1100')
const darkerRed = red.clone().darken(.2)
const lighterRed = red.clone().lighten(.2)
```

``` js
// Immutable
const red = Color('#ee1100')
const darkerRed = red.darken(.2)
const lighterRed = red.lighten(.2)
```

**Comment by MoOx** [comment]
:+1: 
PRs are welcome ;)

**Comment by mindjuice** [comment]
I would prefer an immutable, functional style too.  In fact, without looking at the docs, that was how I started to use ``color`` and it didn't work! :-P

I would be willing to work on a PR for this, but it would break everyone's existing code, which is not advisable.

A few options:

1. Add a function that selects immutable mode or mutable mode, but default to the current mutable behavior if that function is not called.  This keeps compatibility, but adds overhead to every mutative function to check the flag and the extra code in the ``if/else`` bodies.
2. Go ahead and break compatibility, but do a major version number bump so that most ``package.json`` files won't update automatically.  Provide a section in the README with upgrade instructions.
3. Start with option 1 and then move to option 2 in the near future.
4. Fork the project and make the changes there.

Thoughts?

**Comment by MoOx** [comment]
> but it would break everyone's existing code, which is not advisable.

 1.0 didn't exist yet, so we don't care. This project is sort of unmaintained. I am open to lead it (since I have the right for it) but didn't have too much time lately (busy with cssnext, stylelint...).

So please make a PR that break the current API. Major bump with a proper CHANGELOG that contains way to upgrade will do the trick.

**Comment by mindjuice** [comment]
I see.  What do you mean by "since I have the right for it"?  Is there a word missing there or are you referring to license rights?

**Comment by MoOx** [comment]
The original author add me as a collaborator for this repo, so I can push, merge (& even push on npm).

**Comment by lapanoid** [comment]
+1 to this, it was really odd to discover that is mutable

**Comment by wmira** [comment]
this just bit me, i was writing some tests then it hit me... its mutable :( +1 for this pr please

**Comment by MoOx** [comment]
Feel free to make the PR.

**Comment by MoOx** [comment]
I am going to release this breaking change in 1.0 asap.

**Comment by Qix-** [comment]
@MoOx does that mean you handled this? Or does this still need to happen?

**Comment by MoOx** [comment]
I started to work on it, but I didn't finish. Too much work according to the time I allowed me to handle it :)

**Comment by wmira** [comment]
I did a stab at this. I'm still not familiar with some parts of the code but it probably can be used as basis for the actual change. I don't think I have broken anything -- tests still works etc.

**Comment by kevinSuttle** [comment]
https://github.com/facebook/immutable-js could help?

**Comment by ooflorent** [comment]
@kevinSuttle It won't. I'll try to submit a patch.

**Comment by ooflorent** [comment]
NVM #77 achieves it.

**Comment by kevinSuttle** [comment]
Woot

**Comment by Qix-** [comment]
Going to keep this open until #77 is merged. Thanks @ooflorent :+1:

**Comment by dliv** [comment]
Before this is closed, the README should be updated. The first example mutates a color. I'm willing to update the example if a more extensive update of the README isn't being worked on.

**Comment by Qix-** [comment]
Agreed, though I'm working on a makeover branch right now that will have all of that included. You're welcome to submit a PR for the readme for the time being, though.

**Comment by igl** [comment]
Just started to use `color` in our project and have already been bitten by this. :/
I see #77 was reverted. Any plans on still doing this?

**Comment by Qix-** [comment]
@igl Yes - version 1 will have this.

I should probably get to it soon. Every time I sit down to bang out the v1 rewrite it turns into a multi-day thing that ultimately goes by the wayside. I'll dedicate some time to this soon.

**Comment by ericclemmons** [comment]
I came here to request the same, but offer help & support.

A work project is dependent on `color` so I'd be interested in helping out to get v1 out the door with any BC changes in this milestone & punting on feature additions:
> https://github.com/Qix-/color/milestone/1
